### ISSUE TITLE
Ubuntu installation script fails under ZFS, but not EXT4

### ISSUE THREAD

**Issue by apalrd** [neutrinolabs/pulseaudio-module-xrdp#76]
I have a completely fresh (VM) install of xubuntu 21.10 in a completely unmodified configuration. After install, I run apt update, apt upgrade, apt install xrdp, and then proceed to follow the Debian/Ubuntu build instructions.

If the filesystem chosen during install is EXT4, everything works correctly, virtual user sessions have audio, all is well.

If the filesystem chosen during install is ZFS, the process reaches `- Building PA Sources. Log file in /var/tmp/pa-build-testuser-schroot.log` and then `** schroot failed. Check log file /var/tmp/pa-build-testuser-schroot.log`

Here are the content of the log:
```
E: Failed to change directory '/home/testuser/pulseaudio-module-xrdp': No such file or directory
I: The directory does not exist inside the chroot. Use the --directory option to run the command in a different directory
E: Failed to change directory '/home/testuser/pulseaudio-module-xrdp': No such file or directory
I: The directory does not exist inside the chroot. Use the --directory option to run the command in a different directory
E: Failed to change directory '/home/testuser/pulseaudio-module-xrdp': No such file or directory
I: The directory does not exist inside the chroot. Use the --directory option to run the command in a different directory
E: Failed to change directory '/home/testuser/pulseaudio-module-xrdp': No such file or directory
I: The directory does not exist inside the chroot. Use the --directory option to run the command in a different directory
```

The installation is completely unmodified other than choosing ext4 vs zfs in the installer. I am running the installer through the graphical display (not an xrdp session or ssh) in both cases. On the ZFS system many directories are separate mount points (including each individual home directory), I'm not sure if schroot / any other commands used by the script are struggling to traverse mount points.

**Comment by matt335672** [comment]
Hi @apalrd 

An interesting problem.

schroot is a relatively simple beast. By default (if I'm reading this right), the file `/etc/schroot/default/fstab` is used to provide mounts within the schroot. This assumes that `/home` is a single file partition, which of course it won't be on your system.

One quick workaround might be to change this line in `/etc/schroot/default/fstab`:-

```
/home           /home           none    rw,bind         0       0
```

to

```
/home           /home           none    rw,rbind         0       0
```

so that a recursive mount of the home directories is done.

An alternative might be to modify the script to optionally use `/tmp` rather than `$HOME` to store the sources. That may work for you, but could fail on systems using a RAM-backed `/tmp`. I can look at that if you like(?)

**Comment by apalrd** [comment]
I tried both options for completeness and both worked.

For the schroot fstab, I added my user's home directory as another bind mount in `/etc/schroot/default/fstab`. 

I also tried setting `PULSE_DIR=/tmp/pulseaudio.src` and was also able to compile without issues.

The final `pulseaudio.src` directory is small (1.5M), so I don't think it's at risk of failing on a RAM-backed `/tmp`.

Thanks for your help!

**Comment by matt335672** [comment]
Thanks for the feedback.

I had a think about this last night, and I think I'll update the scripts to do the build within the chroot and then copy it out. For the cost of a small copy, this approach will not only cover this case, but will cover NFS home mounts, which I'm pretty sure will also break schroot.

I'll leave this open until I've got something working. If you've got the time to test it for me when it's done, that would be great.

**Comment by matt335672** [comment]
I've updated the script so that it now doesn't depend on /home mounting successfully.

Tested on Ubuntu 20.04LTS with (experimental) ZFS.

My changes are at https://github.com/matt335672/pulseaudio-module-xrdp/tree/remove_home_dependency

The only thing which has actually changed is the `install_pulseaudio_sources_apt_wrapper.sh` script. You can download the updated script directly from here:-

https://raw.githubusercontent.com/matt335672/pulseaudio-module-xrdp/remove_home_dependency/scripts/install_pulseaudio_sources_apt_wrapper.sh

You can just copy that over your existing script. If you do that, `git diff` will show you what the differences are.

**Comment by apalrd** [comment]
I ran this on 21.10 and it worked as expected, so this is what I'll proceed with for my project. Thanks again!

**Comment by matt335672** [comment]
Thanks for the testing - it really helps to get these things independently verified.
